# Generated by Django 4.2.25 on 2025-10-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_notification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeinapp',
            name='type',
        ),
        migrations.AddField(
            model_name='subscribeinapp',
            name='productId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium'), ('scholar', 'scholar')], default='free trial', max_length=100),
        ),
    ]
