# Generated by Django 4.2.25 on 2025-10-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_subscribeinapp_type_subscribeinapp_productid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaries', models.IntegerField(default=1)),
                ('notes', models.IntegerField(default=3)),
                ('reminders', models.IntegerField(default=2)),
                ('smart_search', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
