# Generated by Django 4.2.25 on 2025-10-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usersubscriptionusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium'), ('scholar', 'scholar')], default='free', max_length=100),
        ),
    ]
