# Generated by Django 4.2.25 on 2025-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.IntegerField(default=1),
        ),
    ]
