# Generated by Django 4.2.25 on 2025-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('vendor', 'vendor'), ('user', 'user')], default='user', max_length=100),
        ),
    ]
