# Generated by Django 4.2.25 on 2025-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
