# Generated by Django 4.2.25 on 2026-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_supportmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionusage',
            name='video_extractions',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usersubscriptionusage',
            name='video_notes',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usersubscriptionusage',
            name='video_reminders',
            field=models.IntegerField(default=2),
        ),
    ]
