# Generated by Django 4.2.24 on 2026-03-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_usersubscriptionusage_video_extractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_apple_signin',
            field=models.BooleanField(default=False),
        ),
    ]
