# Generated by Django 4.2.25 on 2025-10-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("visual_representation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImplementationGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KeyInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("mindset", "Mindset"),
                            ("strategy", "Strategy"),
                            ("execution", "Execution"),
                            ("leadership", "Leadership"),
                            ("personal_development", "Personal Development"),
                            ("systems", "Systems"),
                            ("relationships", "Relationships"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("practical_application", models.TextField()),
                ("supporting_quote", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MainArgument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_identified", models.TextField()),
                ("solution_proposed", models.TextField()),
                ("why_it_matters", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OnePageSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=255)),
                ("core_message", models.TextField()),
                ("key_principles", models.JSONField(default=list)),
                ("actionable_takeaways", models.JSONField(default=list)),
                ("memorable_quote", models.TextField()),
                ("who_should_read", models.TextField()),
                ("bottom_line", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ImplementationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "time_estimate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resources_needed", models.JSONField(default=list)),
                ("success_criteria", models.TextField()),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="books.implementationguide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImplementationMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_pitfalls", models.JSONField(default=list)),
                ("quick_wins", models.JSONField(default=list)),
                (
                    "guide",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="books.implementationguide",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FrameworkComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("example", models.TextField()),
                (
                    "framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="books.framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookAnalysisResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=255, unique=True)),
                ("book_title", models.CharField(max_length=255)),
                ("book_author", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "framework",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="book_analysis",
                        to="books.framework",
                    ),
                ),
                (
                    "implementation_guide",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_analysis",
                        to="books.implementationguide",
                    ),
                ),
                (
                    "key_insights",
                    models.ManyToManyField(
                        related_name="book_analyses", to="books.keyinsight"
                    ),
                ),
                (
                    "main_argument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_analysis",
                        to="books.mainargument",
                    ),
                ),
                (
                    "one_page_summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_analysis",
                        to="books.onepagesummary",
                    ),
                ),
            ],
        ),
    ]
