# Generated by Django 4.2.25 on 2025-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_userextractedbooks_bookmarkbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkbook",
            name="book_img",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userextractedbooks",
            name="book_img",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
