# Generated by Django 4.2.25 on 2025-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="book_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notes",
            name="book_title",
            field=models.CharField(max_length=255),
        ),
    ]
