# Generated by Django 4.2.25 on 2025-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_notes_book_id_alter_notes_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="notes",
            name="note_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
