# Generated by Django 4.2.25 on 2025-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_notes_created_at_notes_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='has_notification',
            field=models.BooleanField(default=False),
        ),
    ]
