# Generated by Django 4.2.25 on 2026-01-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_transientvideoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transientvideoupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
