# Generated by Django 4.2.25 on 2026-01-01 02:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_transientvideoupload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transientvideoupload',
            name='video',
            field=models.FileField(default='default.mp4', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
            preserve_default=False,
        ),
    ]
