# Generated by Django 4.2.25 on 2026-01-02 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_alter_transientvideoupload_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractVideoInsights',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=505)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.TextField()),
                ('key_takeaways', models.JSONField(default=list)),
                ('reminders', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_video_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TransientVideoUpload',
        ),
    ]
