# Generated by Django 4.2.25 on 2026-01-02 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_extractvideoinsights_delete_transientvideoupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNotes',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=255)),
                ('has_notification', models.BooleanField(default=False)),
                ('video_title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('note_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
