# Generated by Django 4.2.25 on 2026-01-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_videonotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractvideoinsights',
            name='thumbnail',
        ),
    ]
