# Generated by Django 4.2.24 on 2026-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_remove_extractvideoinsights_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videonotes',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
