# Generated by Django 4.2.25 on 2025-11-22 10:54

import blog.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('headerImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.CharField(blank=True, max_length=10000, null=True, unique=True)),
                ('exerpt', models.TextField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft')], default='draft', max_length=100)),
                ('created_at', models.DateTimeField(default=blog.models.random_created_date)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
