# Generated by Django 4.2.25 on 2025-10-29 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteNotification',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'daily'), ('every-other-day', 'every-other-day'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField()),
                ('noteId', models.CharField(blank=True, max_length=300, null=True)),
                ('notificationId', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
