# Generated by Django 4.2.25 on 2025-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notenotification',
            name='notificationId',
        ),
        migrations.AddField(
            model_name='notenotification',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
