# Generated by Django 4.2.25 on 2025-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notenotification_notificationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notenotification',
            name='reminder_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
